# Generated by Django 3.2.18 on 2023-03-12 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(choices=[(datetime.time(8, 0), '0800'), (datetime.time(9, 0), '0900'), (datetime.time(10, 0), '1000'), (datetime.time(11, 0), '1100'), (datetime.time(12, 0), '1200'), (datetime.time(13, 0), '1300'), (datetime.time(14, 0), '1400'), (datetime.time(15, 0), '1500'), (datetime.time(16, 0), '1600'), (datetime.time(17, 0), '1700'), (datetime.time(18, 0), '1800'), (datetime.time(19, 0), '1900'), (datetime.time(20, 0), '2000')]),
        ),
    ]
