# Generated by Django 3.2.18 on 2023-03-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20230312_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='acknowledged',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='denied',
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('denied', 'denied')], default='pending', max_length=8),
        ),
    ]
