# Generated by Django 3.2.18 on 2023-03-17 11:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('description', models.TextField(default='Menu item description')),
                ('available', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default='00.00', max_digits=4, null=True)),
                ('category', models.CharField(choices=[('starter', 'starter'), ('main', 'main'), ('desert', 'desert')], default='main', max_length=7)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
            ],
        ),
    ]
