# Generated by Django 3.2.18 on 2023-03-17 17:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='default-menu-image_eeth2z.png', max_length=255, verbose_name='image'),
        ),
    ]
